# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/train_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtWidgets , QtGui , QtCore

from views_mangers.main_manger import MainManager




class ocr_app(QtWidgets.QStackedWidget):
    def __init__(self):
        super(ocr_app, self).__init__()

        self.main_manager = MainManager()


        # add widgets to the stack

        self.addWidget(self.main_manager)



        # install signals


        self.main_manager.ReadButton_3.clicked.connect(self.handle_upload_btn_selected)
        self.main_manager.BrowseButton_2.clicked.connect(self.handle_scan_btn)
        self.main_manager.ReadButton_4.clicked.connect(self.hendle_read_btn)


    def handle_upload_btn_selected(self):
        self.main_manager.getfiles()

    def handle_scan_btn(self):
        self.main_manager.readFimage()

    def hendle_read_btn(self):
        self.main_manager.read()




if __name__ == "__main__":
    #import qdarkstyle
    app = QtWidgets.QApplication([])
    w = ocr_app()
    w.show()
    #app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    app.exec_()










